"""Add api_cache table for rate limit protection

Revision ID: 53d985768d5c
Revises: 1c89fb72576b
Create Date: 2025-11-04 17:04:13.031190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53d985768d5c'
down_revision: Union[str, Sequence[str], None] = '1c89fb72576b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_api_cache_expires_at', 'api_cache', ['expires_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_api_cache_expires_at'), 'api_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_index(op.f('ix_api_cache_expires_at'), table_name='api_cache')
    op.drop_index('idx_api_cache_expires_at', table_name='api_cache', postgresql_using='btree')
    op.drop_table('api_cache')
    # ### end Alembic commands ###
